pgweb:
  container_name: pgweb
  restart: always
  image: sosedoff/pgweb
  ports: 
    - "8081:8081" 
  links: 
    - postgres:postgres
  environment:
    - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres