apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: blah

# kustomize bug, helmGlobals gets removed for some reason when we do an `kustomize edit`
helmGlobals:
  chartHome: ../

helmCharts:
