apiVersion: builtin
kind: ConfigMapGenerator
behavior: merge
metadata:
  name: argocd-cm
  namespace: argocd
literals:
  - "timeout.reconciliation=15s"
  - "kustomize.buildOptions=--load-restrictor LoadRestrictionsNone --enable-helm"