---
# Source: pgweb/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ingress-controller-pgweb
  labels:
    helm.sh/chart: pgweb-0.1.0
    app.kubernetes.io/name: pgweb
    app.kubernetes.io/instance: ingress-controller
    app.kubernetes.io/version: "0.11.10"
    app.kubernetes.io/managed-by: Helm
